### ISSUE TITLE
老哥，请问这个具体咋用😂

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [2BAB/Seal#16]
我看中文文档介绍在根项目的build.gradle里配置classpath，但是现在新的AndroidStudio里已经没classpath了，不知道该咋配😂
````groovy
dependencies {
        classpath("com.android.tools.build:gradle:7.1.2")
        classpath("me.2bab:seal:3.2.0")
    }
````
````groovy
plugins {
    id 'com.android.application' version '7.2.1' apply false
    id 'com.android.library' version '7.2.1' apply false
    id 'org.jetbrains.kotlin.android' version '1.7.10' apply false
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
````
还有plugin的id是配置在这里面的吗？是跟着上面的一起写吗？
还有seal的配置是写在哪的，我都不知道咋写😥

**Comment by 2BAB** [comment]
1. 你还是可以在根目录的 `build.gradle(.kts)` 添加 `classpath("com.android.tools.build:gradle:7.1.2")` ，然后正常在你的 Android Application 模块的 `build.gradle(.kts)` 添加 `id("me.2bab.seal")`，并使用 DSL 配置相应参数。
2. 如果想完全切到 `plugins` 的语法，目前我还没提供（或说发布）相关的 plugin 坐标，可以使用如下形式引用。最近几天在做下个版本了（兼容 7.1 7.2 的 AGP），会加上 plugin 的坐标。
<img width="515" alt="image" src="https://user-images.githubusercontent.com/5710495/184463529-6f73673b-7323-4e89-9f68-addfc0594541.png">
https://docs.gradle.org/current/userguide/plugins.html

**Comment by SaltedFish-Extreme** [comment]
@2BAB 我不会用DSL😂也不大会用plugins😥我这边只是用as自动配置的安卓项目，只会添加依赖，没大改过别的东西，麻烦老哥出一个详细点的小白教程😭

**Comment by 2BAB** [comment]
不会就去学吧，基本每个插件提供的引导都是这样哈，没办法更详细。

**Comment by SaltedFish-Extreme** [comment]
> 不会就去学吧，基本每个插件提供的引导都是这样哈，没办法更详细。

不是吧老哥😂之前用DSLAdapter的时候，那个开发者老哥因为有不会用dsl的都专门写了个kt普通用法的demo，java没法用那实在没办法，不过我能用的东西都会给java开发专门写个扩展函数，因为我本身原来就是做java的☺️感觉老哥你这插件适用度不行，能用的人也太少了，太小众的插件也推广不出来，很多人也并不会因为一个插件费很多功夫去学一个语法甚至语言，当然老哥你开发的想让谁用就用谁用，想怎么搞就怎么搞，我就说下我的看法😅

**Comment by SaltedFish-Extreme** [comment]
说起来，我最后还是找到了解决办法，只要在replace里面去掉android，只保留后面的属性，也可以编译通过，还有老哥，我再说些实际些的东西，我们那边原来只有外包才使用kotlin，因为原来16-18年的代码都是那些外包追求开发速度，用0.几版本的kotlin做，后面出了一堆问题，最后拿回来都换成java了，很恶心，都是一行一行代码复制修改的，所以其实新东西并不是最好的，大部分公司还是以稳定和能随着时间迭代不会出问题为首要选择，dsl说不定哪天也会出一堆的问题，所以我觉得还是大部分人都会用并且在实际项目上应用时间比较长的，才适合开放出来给大众用😊
