### ISSUE TITLE
Error:Could not get unknown property 'applicationVariants' for object of type com.android.build.gradle.LibraryExtension.

### ISSUE THREAD

**Issue by sunfusheng** [2BAB/Seal#2]
Error:Could not get unknown property 'applicationVariants' for object of type com.android.build.gradle.LibraryExtension.

**Comment by 2BAB** [comment]
Sorry for that, Seal only works for the project which applied the plugin of application.

**Comment by Kolyall** [comment]
Seems you try to use `android.applicationVariants` in `library` module.
Tutorial:
In `app` module use `apply plugin: 'com.android.application'` and `android.applicationVariants` 
In `library` module use `apply plugin: 'com.android.library'` and `android.libraryVariants`

**Comment by 2BAB** [comment]
> Seems you try to use `android.applicationVariants` in `library` module.
> Tutorial:
> In `app` module use `apply plugin: 'com.android.application'` and `android.applicationVariants`
> In `library` module use `apply plugin: 'com.android.library'` and `android.libraryVariants`

It's intentional because we met the merge-problems almost in the application building. On the 2.0.0, I added the plugin check, like below:

``` groovy
 if (!project.plugins.hasPlugin(AppPlugin.class)) {
            throw new IllegalStateException("'com.android.application' plugin required.")
        }
```

If you want to use it in library modules, please leave the reason here that we can discuss if it's needed. Thank you! @Kolyall
